"""Ontology graph operations package."""

from .ontology import (
    append_op,
    append_schema,
    create_entity,
    create_relation,
    delete_entity,
    generate_id,
    get_entity,
    get_related,
    list_entities,
    load_graph,
    load_schema,
    merge_schema,
    query_entities,
    resolve_safe_path,
    update_entity,
    validate_graph,
    write_schema,
)

__all__ = [
    "append_op",
    "append_schema",
    "create_entity",
    "create_relation",
    "delete_entity",
    "generate_id",
    "get_entity",
    "get_related",
    "list_entities",
    "load_graph",
    "load_schema",
    "merge_schema",
    "query_entities",
    "resolve_safe_path",
    "update_entity",
    "validate_graph",
    "write_schema",
]
